apiVersion: v2
name: codesys-pod
description: Codesys Control ARM32 Runtime (Installer Pattern)
type: application
version: 1.0.3
appVersion: "4.18.0.0"
keywords:
  - codesys
  - plc
  - industrial
  - arm
  - iiot
home: https://github.com/Embernet-ai/codesys_arm_64
icon: https://embernet-ai.github.io/codesys_arm_64/codesys-icon.png
maintainers:
  - name: Embernet-ai
    email: support@embernet.ai
annotations:
  catalog.cattle.io/display-name: Codesys Control ARM32
  catalog.cattle.io/os: linux
  catalog.cattle.io/arch: arm64,amd64
  catalog.cattle.io/certified: partner
  catalog.cattle.io/release-name: codesys-pod
  catalog.cattle.io/ui-component: "true"
